# Configurações de performance do PostgreSQL para Moodle
# Gerado com pgtune: https://pgtune.leopard.in.ua/
# DB Version: 17 | OS: linux | DB Type: web
# RAM: 1 GB | CPUs: 1 | Connections: 200 | Storage: ssd

max_connections = 200
shared_buffers = 256MB
effective_cache_size = 768MB
maintenance_work_mem = 64MB
checkpoint_completion_target = 0.9
wal_buffers = -1
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 1310kB
huge_pages = try
min_wal_size = 1GB
max_wal_size = 4GB
