; Configurações PHP requeridas pelo Moodle
; Ref: MDL-71390 — suporte a sites com 1000+ cursos, atividades e usuários
max_input_vars = 5000

; Tamanho máximo de upload e post
upload_max_filesize = 200M
post_max_size = 206M
